// src/lib/PageControlItem/PageControlItem.tsx
import * as React from 'react';

/**
 * PageControlItem — React build.
 *
 * Single segment/dot atom of the PageControl widget. Mirrors the API and
 * markup of PageControlItem.svelte and shares styles via
 * src/lib/PageControlItem/PageControlItem.css.
 */

export type PageControlItemType = 'segment' | 'point';

export interface PageControlItemProps
  extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'children'> {
  type?: PageControlItemType;
  active?: boolean;
}

export const PageControlItem = React.forwardRef<HTMLSpanElement, PageControlItemProps>(
  function PageControlItem({ type = 'segment', active = false, ...rest }, ref) {
    return (
      <span
        ref={ref}
        className="antares-page-control-item"
        data-type={type}
        data-active={active ? 'true' : undefined}
        {...rest}
      />
    );
  }
);

export default PageControlItem;

// src/lib/PageControlItem/PageControlItem.svelte
<script>
  /**
   * PageControlItem — Svelte 5 markup.
   *
   * Single segment/dot atom of the PageControl widget. Pure visual; no
   * interaction states (no hover/pressed/disabled). Visual styles live in
   * ./PageControlItem.css (imported globally via src/app.css).
   *
   * @typedef {'segment' | 'point'} Type
   */

  let {
    type = 'segment',
    active = false,
    ...rest
  } = $props();
</script>

<span
  class="antares-page-control-item"
  data-type={type}
  data-active={active ? 'true' : null}
  {...rest}
></span>
